/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package chatbot;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import java.applet.AudioClip;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
/**
 *
 * @author gamei
 */
public class Interfaz extends javax.swing.JFrame {
    String pregunta ,respuesta ,preguntagenerada;
    boolean reproduciendo=false;
    AudioClip sonido1,sonido2,alive;
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NameBot = new javax.swing.JLabel();
        online = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pantalla = new javax.swing.JTextArea();
        enviar = new javax.swing.JButton();
        texto = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameBot.setText("ChatBot");
        getContentPane().add(NameBot, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 67, -1));
        getContentPane().add(online, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 101, 21));

        jButton1.setText("Enseñar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 14, -1, -1));

        pantalla.setEditable(false);
        pantalla.setColumns(20);
        pantalla.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        pantalla.setRows(5);
        jScrollPane1.setViewportView(pantalla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 310, 420));

        enviar.setText("Enviar");
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });
        getContentPane().add(enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 477, -1, -1));

        texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoActionPerformed(evt);
            }
        });
        getContentPane().add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 476, 183, 30));

        jPanel1.setBackground(new java.awt.Color(12, 215, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 50));

        jPanel2.setBackground(new java.awt.Color(243, 243, 243));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 202, 228)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 310, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoActionPerformed

    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarActionPerformed
       Thread hilo = new Thread(new Runnable(){
           @Override
           public void run(){
               try{
                   pregunta =texto.getText();
                   respuesta =(new BuscarDatos().translate(texto.getText()));
                   preguntagenerada =(new BuscarDatos().translate(generarpregunta()));
                   pantalla.append("Usted: "+texto.getText()+"\n");
                   if(respuesta.equalsIgnoreCase("ok")){
                       pantalla.append("Cortana: Podrias enseñarme que debo responder si me dicen '"+pregunta+"' porfavor (si/no)\n");
                       String respuestUsuario= JOptionPane.showInputDialog("Deseas enseñarle? (si/no)");
                       if (respuestUsuario.equalsIgnoreCase("si")){
                           String respuestUsuarioPregunta=JOptionPane.showInputDialog("Que responder a '"+pregunta+"'");
                           Leer aprender = new Leer();
                           String nuevapalabra = aprender.preguntanueva(pregunta,respuestUsuarioPregunta);
                           aprender.guardar(aprender.leertxt("datos.txt"),nuevapalabra);
                           
                       }
                   }
                   texto.setText("");
                   animacionEscribir(respuesta);
                   int probabilidad = mitadProbabilidad();
                   if(probabilidad>5){
                       animacionPregunta(preguntagenerada);
                       if(preguntagenerada.equalsIgnoreCase("pongamos musica")&& reproduciendo != true){
                           alive= java.applet.Applet.newAudioClip(getClass().getResource("./alive.waw"));
                           alive.play();
                       }
                   }
               }catch(Exception e){
                   
               }
           }
       });
       hilo.start();
       
    }//GEN-LAST:event_enviarActionPerformed
    public String generarpregunta(){
        int numero;
        numero= (int)(Math.random()*9)+1;
        String preguntaAleatoria = Integer.toString(numero);
        String preguntacompletada= preguntaAleatoria+"p";
        return preguntacompletada;
    }
    public int mitadProbabilidad(){
        int numero;
        numero = (int)(Math.random()*9)+1;
        return numero;
    }
    public void animacionEscribir(String respuestaxd)throws InterruptedException,URISyntaxException,IOException{
        sonido1 = java.applet.Applet.newAudioClip(getClass().getResource("./mensajellegada.wav"));
        sonido2 = java.applet.Applet.newAudioClip(getClass().getResource("./pop.wav"));
        Thread.sleep(generarRandom());
        online.setForeground(Color.blue);
        sonido2.play();
        online.setText("Visto");
        Thread.sleep(generarRandom());
        online.setText("Escribiendo...");
        Thread.sleep(generarRandom());
        online.setText("");
        sonido1.play();
        pantalla.append("Cortana: "+respuestaxd+"\n");
        if(pregunta.equalsIgnoreCase("reproducir musica")){
            reproduciendo= true;
            Desktop.getDesktop().browse(new URI ("http://www.youtube.com/watch?v=I_izvAbhExY"));
        }
    }
    public void animacionPregunta(String respuestaxd) throws InterruptedException{
        sonido1= java.applet.Applet.newAudioClip(getClass().getResource("./mensajellegada.wav"));
        Thread.sleep(1500);
        online.setText("Escribiendo...");
        Thread.sleep(1000);
        online.setText("");
        sonido1.play();
        pantalla.append("Cortana: "+respuestaxd+"\n");
    }
    public int generarRandom(){
        int numero;
        numero = (int)(Math.random()*4000)+1000;
        return numero;
    }
    public void fijarTexto(){
        pantalla.append("Maquina: "+respuesta+"\n");
        texto.setText("");
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String UsuarioPregunta = JOptionPane.showInputDialog("Ingrese Pregunta");
       String respuestUsuarioPregunta= JOptionPane.showInputDialog("Que responder a '"+UsuarioPregunta+"'");
       Leer aprender = new Leer();
       String nuevapalabra = aprender.preguntanueva(UsuarioPregunta,respuestUsuarioPregunta);
       aprender.guardar(aprender.leertxt("datos.txt"),nuevapalabra);
    }//GEN-LAST:event_jButton1ActionPerformed
    public JButton enviarPresionado(){
        return enviar;
    }
    public void setPantalla(){
        pantalla.append("Maquina: "+respuesta+"\n");
    }
    public JTextArea regresaPantalla(){
        return pantalla;
    }
    public JTextField regresaTexto(){
        return texto;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NameBot;
    private javax.swing.JButton enviar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel online;
    private javax.swing.JTextArea pantalla;
    private javax.swing.JTextField texto;
    // End of variables declaration//GEN-END:variables
}
